<a href="https://colab.research.google.com/github/NishmithaJR/Principles-of-Data-Science/blob/main/Write_a_pogram_to_perform_numerical_analysis_and_data_manipulation_using_numpy_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) Create numpy array

In [ ]:
import numpy as np
#create an ID array
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


2) Access and manipulate elements in the array

In [ ]:
#Accessing elements from the arry
arr1[2]
#Change an element from the array
arr1[2]=5
arr1

array([1, 2, 5])

3) Create a 2-dimensional array and check the shape of the array

In [ ]:
#Create 20 array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


4) Access elements from the 2D array using index positions

In [ ]:
#Accessing elements from the array
print(arr2[0][2])
print(arr2[0,2])
print(arr2[0,-1])
print(arr2[-1,0])

3
3
3
4


5)Creare an array of type string

In [ ]:
#Array of type string
arr3=np.array(['India','China','USA','Mexico'])
print(arr3)

['India' 'China' 'USA' 'Mexico']


In [ ]:
arr3[1]

'China'

6) Using the arrange() and linspace() function to evenly space values in a specified interval

In [ ]:
#Array of evenly spaced values in a specified interval
arr=np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
#Array of evenly spaced number in a specified interval
arr=np.linspace(0,10,20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


7) Cretae an array of random values between 0 and 1 in a given shape

In [ ]:
#Array of random values between 0 and 1 in agiven shape
arr=np.random.rand(10)
print(arr)
print('\n')
arr=np.random.rand(3,4)
print(arr)

[0.1312415  0.44559721 0.149097   0.41824655 0.46476223 0.76893651
 0.81406706 0.34289821 0.05952458 0.27783776]


[[0.02048757 0.97079427 0.68386741 0.85176328]
 [0.12943635 0.16378686 0.26109425 0.61928531]
 [0.99029512 0.2306524  0.04413424 0.16775363]]


8) Create an array of constant values in a given shape

In [ ]:
#Array of constant values in a given shape
print(np.full((4,6),10))

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


9) Repeat each element of an array by a specified number of times using repeat() and tile() functions

In [ ]:
#Create an array by repetition 
#Repeat each element of an array by a specified number of times
arr=[0,1,2]
print(np.repeat(arr,3))

[0 0 0 1 1 1 2 2 2]


In [ ]:
#Repeat an array by a specified number of times
arr=[0,1,2]
print(np.tile(arr,3))

[0 1 2 0 1 2 0 1 2]


10) Create an identity matrix using eye() and identity() functions

In [ ]:
#Create an identity matrix
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
identity_matrix=np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


11) Create a 5*5 2D array for random numbers between 0 and 1

In [ ]:
arr=np.random.rand(5,5)
print(arr)

[[0.14733541 0.52817981 0.06469303 0.12479386 0.591861  ]
 [0.81619962 0.5386092  0.03355767 0.32721732 0.67429592]
 [0.03000999 0.31773152 0.57018811 0.17432051 0.7393409 ]
 [0.55596329 0.32792742 0.19487927 0.79176846 0.16692356]
 [0.02221623 0.78341319 0.04129267 0.65035248 0.29153225]]


12) Sum an array along the column

In [ ]:
#Sum along the column
print(np.sum(arr,axis=0))

[1.57172454 2.49586113 0.90461075 2.06845262 2.46395363]


13) Sum an array along the row

In [ ]:
#Sum along the row
print(np.sum(arr,axis=1))

[1.45686311 2.38987973 1.83159102 2.03746199 1.78880682]


14) Calculate the mean, median, standard deviation and variance

In [ ]:
print(np. mean(arr))
print(np. median(arr))
print(np. std(arr))
print(np. var(arr))

0.38018410718412554
0.32721732035814954
0.2693421905887199
0.07254521563113031


15) Sort an array along the row using sort() function

In [ ]:
#Sort an array
arr=np.random.rand(5,5)
print(arr)

[[0.07213128 0.03648229 0.10552063 0.44740409 0.97388256]
 [0.05803896 0.77034256 0.70377268 0.04825061 0.67335373]
 [0.5907241  0.78675588 0.97008434 0.86336675 0.74209927]
 [0.38744596 0.89049079 0.54425418 0.03177925 0.79009079]
 [0.8491438  0.97319817 0.53123734 0.86191413 0.75259176]]


In [ ]:
#Sort along the row
print(np.sort(arr,axis=1))

[[0.03648229 0.07213128 0.10552063 0.44740409 0.97388256]
 [0.04825061 0.05803896 0.67335373 0.70377268 0.77034256]
 [0.5907241  0.74209927 0.78675588 0.86336675 0.97008434]
 [0.03177925 0.38744596 0.54425418 0.79009079 0.89049079]
 [0.53123734 0.75259176 0.8491438  0.86191413 0.97319817]]


16) Append elements to an array using the append() function

In [ ]:
#Append elements of an array
arr=np.array([4,5,6,7])
arr1=np.append(arr,8)
arr1

array([4, 5, 6, 7, 8])

In [ ]:
arr2=np.append(arr,[9,10,11])
print(arr2)

[ 4  5  6  7  9 10 11]


17) Delete multiple elements in an array

In [ ]:
#Delete multile elements
arr2=np.array([4,5,6,7,8,9,10,11])
print(arr2)
print('\n')
arr5=np.delete(arr2,[1,4])
print(arr5)

[ 4  5  6  7  8  9 10 11]


[ 4  6  7  9 10 11]


18) Concatenate elements from 2 arrays

In [ ]:
#Combine and split an array
arr1=np.array([[1,2,3,4],[1,2,3,4]])
arr2=np.array([[5,6,7,8],[5,6,7,8]])
#Combine the array items by column
cat=np.concatenate((arr1,arr2),axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [ ]:
#Combine the array items by row 
cat=np.concatenate((arr1,arr2),axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
